[package]
name = "laintrace"
version = "0.1.0"
edition = "2021"
authors = ["_relsa"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pnet]
version = "0.28.0"
